### ISSUE TITLE
How much ETH can v1 of this lottery safely handle without creating adverse incentives for miners?

### ISSUE THREAD

**Issue by jack-fraser** [jack-fraser/Ethereum-Lottery#1]
In order for malicious miners to generate value in this lottery system they need to withhold possible hashes that cause them to lose on their lotto bets. Miners that withhold these hashes would drastically reduce their hash rates and as a result would miss out on the block rewards they otherwise would have received. There exists some equilibrium that would maximize the amount of ETH the lottery pool could handle while not giving miners the incentive to withhold blocks.

**Comment by jack-fraser** [comment]
The largest amount of hashing power a theoretical attacker could possess is 50%. If an attacker controlled more than 50% there would be other valid concerns about the network that would supersede the concerns over the lottery smart contract.

In order for the 50% attacker to exert their influence on the block they would have to reject blocks that would result in them losing money in the lottery. This action of rejecting valid blocks would lower their expected return.

In v1 of the ethereum lottery our 50% attacker would decrease their real hash rate by 50% because they would have to come up with two valid blocks (on average) before anyone else would be able come up with one.

 Normal Hashing % | Calculation | Real Hashing % | (+/-) Percentage Change
|---|---|---|---|
50% | `.5 * .5 = .25` | 25% | -50%
20% | `.2 * .2 = .04` | 4% | -80%
10% | `.1 *.1 = .01` | 1% | -90%
1%   | `.01 * .01 = .0001` | .01% | -99%

Note: This attack becomes less and less efficient as the attacker controls less and less of the total hashing power of the network.

**Comment by fernandogarcialoaiza** [comment]
Hello Jack, can you contact me fernando.garcia@zencillo.com. Thanks
